### ISSUE TITLE
Remove `&& \` from nifi Dockerfile

### ISSUE THREAD

**Issue by misha-wakerman** [brightsparklabs/dockerfiles#2]
https://github.com/brightsparklabs/dockerfiles/blob/master/src/nifi/Dockerfile#L25

The `&& \` from line 25 should not be there and causes the build to fail. This issue is fixed on develop (https://github.com/brightsparklabs/dockerfiles/blob/develop/src/nifi/Dockerfile).

**Comment by thomas-anderson-bsl** [comment]
No longer relevant - Dockerfile has been fixed
